version: '3.8'

services:
  insurance-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  insurance-app:
    build: .
    depends_on:
      - insurance-db
    ports:
      - "8080:8080"