version: '3.8'

services:
  insurance-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    profiles:
      - prod

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=yourpassword
    command: [ "redis-server", "--requirepass", "yourpassword" ]
    profiles:
      - dev
      - prod

  insurance-app-dev:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: yourpassword
    ports:
      - "8081:8080"
    depends_on:
      - redis
    profiles:
      - dev

  insurance-app-prod:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: yourpassword
    depends_on:
      - insurance-db
      - redis
    ports:
      - "8080:8080"
    profiles:
      - prod
