version: '3.8'

services:
  insurance-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    profiles:
      - prod

  redis-cache:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
    command: [ "redis-server", "--requirepass", "password" ]
    profiles:
      - dev
      - prod

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: insurance-db
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin1
      KEYCLOAK_ADMIN_PASSWORD: aRentetaRmIt
    ports:
      - "8080:8080"
    command: ["start-dev"]
    depends_on:
      - insurance-db
    profiles:
      - prod

  insurance-app-dev:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      - redis-cache
    profiles:
      - dev

  insurance-app-prod:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: prod
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
      OAUTH2_ISSUER_URI: http://keycloak:8080/realms/myrealm
    depends_on:
      - insurance-db
      - redis-cache
      - keycloak
    ports:
      - "8081:8081"
    profiles:
      - prod
