version: '3.8'

services:
  insurance-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    profiles:
      - prod

  redis-cache:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
    command: [ "redis-server", "--requirepass", "password" ]
    profiles:
      - dev
      - prod

  insurance-app-dev:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: dev
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      - redis-cache
    profiles:
      - dev

  insurance-app-prod:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: prod
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    depends_on:
      - insurance-db
      - redis-cache
    ports:
      - "8081:8081"
    profiles:
      - prod
