version: '3.8'

services:
  insurance-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    profiles:
      - prod

  insurance-app-dev:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8081:8080"
    profiles:
      - dev

  insurance-app-prod:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - insurance-db
    ports:
      - "8080:8080"
    profiles:
      - prod
