spring.application.name: insurance

spring:
  application:
    name: insurance
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:changelog/changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  error:
    include-message: always
    include-binding-errors: always

# Including server.error configurations to see detailed error messages in API responses.