# PostgreSQL database configuration (for production)

spring:
  datasource:
    url: jdbc:postgresql://insurance-db/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:changelog/changelog-master.xml
    contexts: postgres
  data:
    web:
      pageable:
        default-page-size: 10
