spring.application.name: insurance
# H2 Database Configuration (for development/testing)
# Comment the following lines to use PostgreSQL instead of H2

spring:
  application:
    name: insurance
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:changelog/changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  error:
    include-message: always
    include-binding-errors: always
    port: 8080

# Including server.error configurations to see detailed error messages in API responses.

# PostgreSQL database configuration (for production)
# Uncomment the following lines to use PostgreSQL instead of H2
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  liquibase:
#    change-log: classpath:changelog/changelog-master.xml
#  server:
#    port: 8080


