spring:
  profiles:
    active: dev # development profile - dev (by default)
                # change to production profile - prod
  data:
    web:
      pageable:
        default-page-size: 10
  liquibase:
    change-log: classpath:changelog/changelog-master.xml

server:
  error:
    include-message: always
    include-binding-errors: always
    port: 8080