spring:
  application:
    name: insurance
  profiles:
    active: dev # development profile - dev (by default)
                # change to production profile - prod

  liquibase:
    change-log: classpath:changelog/changelog-master.xml

  data:
    web:
      pageable:
        default-page-size: 10
    redis:
      host: ${REDIS_HOST:redis-cache}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
