# H2 Database Configuration (for development/testing)

spring:
  application:
    name: insurance
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:changelog/changelog-master.xml
    contexts: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        default-page-size: 10
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:yourpassword}

server:
  error:
    include-message: always
    include-binding-errors: always
    port: 8080